POST http://localhost:8080/user/register?user=feder&pwd=123&email=lol@gmail.com&educator=true
###uid=3
POST http://localhost:8080/user/login?user=feder&pwd=123
###
POST http://localhost:8080/tournament/create_t?uid=3&tname=TOURNAMENT
###idT=3
POST http://localhost:8080/user/register?user=feder2&pwd=123&email=lol@gmail.com&educator=true
###uid=4
POST http://localhost:8080/tournament/3/addCollaborator?uid=3&cid=4